// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1, arg2) {
  return window['go']['main']['App']['ApplyUpdate'](arg1, arg2);
}

export function CheckExpiringCerts() {
  return window['go']['main']['App']['CheckExpiringCerts']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CopyFilesToClipboard(arg1) {
  return window['go']['main']['App']['CopyFilesToClipboard'](arg1);
}

export function CreateSubfolder(arg1) {
  return window['go']['main']['App']['CreateSubfolder'](arg1);
}

export function CsvTemplate() {
  return window['go']['main']['App']['CsvTemplate']();
}

export function DashboardStats() {
  return window['go']['main']['App']['DashboardStats']();
}

export function DeleteSubfolder(arg1) {
  return window['go']['main']['App']['DeleteSubfolder'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExportXlsxTemplate(arg1) {
  return window['go']['main']['App']['ExportXlsxTemplate'](arg1);
}

export function FileDelete(arg1) {
  return window['go']['main']['App']['FileDelete'](arg1);
}

export function FileImport(arg1) {
  return window['go']['main']['App']['FileImport'](arg1);
}

export function FileList(arg1) {
  return window['go']['main']['App']['FileList'](arg1);
}

export function FileRename(arg1) {
  return window['go']['main']['App']['FileRename'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFileDataUrl(arg1) {
  return window['go']['main']['App']['GetFileDataUrl'](arg1);
}

export function GetWorkspaceConfig() {
  return window['go']['main']['App']['GetWorkspaceConfig']();
}

export function GetWorkspaceFileUrl(arg1) {
  return window['go']['main']['App']['GetWorkspaceFileUrl'](arg1);
}

export function ImportProductSetsFromXlsx(arg1) {
  return window['go']['main']['App']['ImportProductSetsFromXlsx'](arg1);
}

export function LicenseActivate(arg1) {
  return window['go']['main']['App']['LicenseActivate'](arg1);
}

export function LicenseCheck() {
  return window['go']['main']['App']['LicenseCheck']();
}

export function LicenseInfo() {
  return window['go']['main']['App']['LicenseInfo']();
}

export function LicenseLogout() {
  return window['go']['main']['App']['LicenseLogout']();
}

export function LicenseRequestCode(arg1, arg2) {
  return window['go']['main']['App']['LicenseRequestCode'](arg1, arg2);
}

export function LicenseStartTrial() {
  return window['go']['main']['App']['LicenseStartTrial']();
}

export function MetadataGet(arg1, arg2) {
  return window['go']['main']['App']['MetadataGet'](arg1, arg2);
}

export function MetadataUpdate(arg1) {
  return window['go']['main']['App']['MetadataUpdate'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenFileWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenFileWithDefaultApp'](arg1);
}

export function ProductSetCreate(arg1) {
  return window['go']['main']['App']['ProductSetCreate'](arg1);
}

export function ProductSetDelete(arg1) {
  return window['go']['main']['App']['ProductSetDelete'](arg1);
}

export function ProductSetList() {
  return window['go']['main']['App']['ProductSetList']();
}

export function ProductSetStats(arg1) {
  return window['go']['main']['App']['ProductSetStats'](arg1);
}

export function RenameProductSet(arg1, arg2) {
  return window['go']['main']['App']['RenameProductSet'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function ShowFilesInExplorer(arg1) {
  return window['go']['main']['App']['ShowFilesInExplorer'](arg1);
}

export function UpdateProductSetInfo(arg1) {
  return window['go']['main']['App']['UpdateProductSetInfo'](arg1);
}

export function UpdateWorkspaceConfig(arg1) {
  return window['go']['main']['App']['UpdateWorkspaceConfig'](arg1);
}

export function WindowHideToTray() {
  return window['go']['main']['App']['WindowHideToTray']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowQuit() {
  return window['go']['main']['App']['WindowQuit']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}

export function WorkspaceCreate(arg1) {
  return window['go']['main']['App']['WorkspaceCreate'](arg1);
}

export function WorkspaceCurrent() {
  return window['go']['main']['App']['WorkspaceCurrent']();
}

export function WorkspaceList() {
  return window['go']['main']['App']['WorkspaceList']();
}

export function WorkspaceOpen(arg1) {
  return window['go']['main']['App']['WorkspaceOpen'](arg1);
}

export function WorkspaceSwitch(arg1) {
  return window['go']['main']['App']['WorkspaceSwitch'](arg1);
}
