// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {updater} from '../models';
import {frontend} from '../models';

export function ApplyUpdate(arg1:string,arg2:string):Promise<main.ApiResult_bool_>;

export function CheckExpiringCerts():Promise<main.ApiResult____3_string_>;

export function CheckUpdate():Promise<main.ApiResult_certmanager_internal_updater_UpdateInfo_>;

export function CopyFilesToClipboard(arg1:Array<string>):Promise<main.ApiResult_bool_>;

export function CreateSubfolder(arg1:main.SubfolderCreateRequest):Promise<main.ApiResult_bool_>;

export function CsvTemplate():Promise<main.ApiResult_string_>;

export function DashboardStats():Promise<main.ApiResult_main_DashboardStats_>;

export function DeleteSubfolder(arg1:main.DeleteSubfolderRequest):Promise<main.ApiResult_bool_>;

export function DownloadUpdate(arg1:updater.UpdateInfo):Promise<main.ApiResult_string_>;

export function ExportXlsxTemplate(arg1:string):Promise<main.ApiResult_bool_>;

export function FileDelete(arg1:Array<string>):Promise<main.ApiResult_bool_>;

export function FileImport(arg1:main.ImportFileRequest):Promise<main.ApiResult___main_FileEntry_>;

export function FileList(arg1:main.FileListRequest):Promise<main.ApiResult___main_FileEntry_>;

export function FileRename(arg1:main.FileRenameRequest):Promise<main.ApiResult_bool_>;

export function GetAppVersion():Promise<string>;

export function GetFileDataUrl(arg1:string):Promise<main.ApiResult_string_>;

export function GetWorkspaceConfig():Promise<main.ApiResult_main_WorkspaceConfig_>;

export function GetWorkspaceFileUrl(arg1:string):Promise<main.ApiResult_string_>;

export function ImportProductSetsFromXlsx(arg1:string):Promise<main.ApiResult___main_ProductSetInfo_>;

export function LicenseActivate(arg1:main.LicenseActivateRequest):Promise<main.ApiResult_main_LicenseStatus_>;

export function LicenseCheck():Promise<main.ApiResult_main_LicenseStatus_>;

export function LicenseInfo():Promise<main.ApiResult_main_LicenseInfo_>;

export function LicenseLogout():Promise<main.ApiResult_bool_>;

export function LicenseRequestCode(arg1:string,arg2:string):Promise<main.ApiResult_bool_>;

export function LicenseStartTrial():Promise<main.ApiResult_main_LicenseStatus_>;

export function MetadataGet(arg1:string,arg2:string):Promise<main.ApiResult_main_FileMetadata_>;

export function MetadataUpdate(arg1:main.MetadataUpdateRequest):Promise<main.ApiResult_bool_>;

export function OpenDirectoryDialog(arg1:string):Promise<main.ApiResult_string_>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<main.ApiResult_string_>;

export function OpenFileWithDefaultApp(arg1:string):Promise<main.ApiResult_bool_>;

export function ProductSetCreate(arg1:main.ProductSetCreateRequest):Promise<main.ApiResult_main_ProductSetInfo_>;

export function ProductSetDelete(arg1:string):Promise<main.ApiResult_bool_>;

export function ProductSetList():Promise<main.ApiResult___main_ProductSetInfo_>;

export function ProductSetStats(arg1:string):Promise<main.ApiResult_main_ProductSetStats_>;

export function RenameProductSet(arg1:string,arg2:string):Promise<main.ApiResult_bool_>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<main.ApiResult_string_>;

export function SaveTextFile(arg1:string,arg2:string):Promise<main.ApiResult_bool_>;

export function Search(arg1:string):Promise<main.ApiResult_main_SearchResult_>;

export function ShowFilesInExplorer(arg1:Array<string>):Promise<main.ApiResult_bool_>;

export function UpdateProductSetInfo(arg1:main.ProductSetUpdateRequest):Promise<main.ApiResult_bool_>;

export function UpdateWorkspaceConfig(arg1:main.WorkspaceConfig):Promise<main.ApiResult_main_WorkspaceConfig_>;

export function WindowHideToTray():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimize():Promise<void>;

export function WindowQuit():Promise<void>;

export function WindowShow():Promise<void>;

export function WindowToggleMaximize():Promise<void>;

export function WorkspaceCreate(arg1:string):Promise<main.ApiResult_main_WorkspaceInfo_>;

export function WorkspaceCurrent():Promise<main.ApiResult_main_WorkspaceInfo_>;

export function WorkspaceList():Promise<main.ApiResult___main_WorkspaceInfo_>;

export function WorkspaceOpen(arg1:string):Promise<main.ApiResult_main_WorkspaceInfo_>;

export function WorkspaceSwitch(arg1:string):Promise<main.ApiResult_main_WorkspaceInfo_>;
