//go:build !windows

package updater

// updaterBinary is a placeholder for non-Windows builds so that the package
// compiles during development on Linux/macOS. The real Windows binary is
// generated by scripts/build-server.sh before wails build.
var updaterBinary []byte
